# CPU Configuration for OCR Batch Processing
# Optimized for CPU-only execution

# Processing Configuration
device: "cpu"
num_workers: 4  # Adjust based on CPU cores
batch_size: 8
timeout: 60  # Timeout per document in seconds

# OCR Model Settings
model:
  type: "easyocr"
  languages: ["en"]
  gpu: false
  quantize: true  # Use quantized models for faster CPU inference
  
  # EasyOCR specific settings for CPU optimization
  easyocr:
    canvas_size: 1920  # Smaller canvas for faster processing
    mag_ratio: 1.0
    text_threshold: 0.7
    low_text: 0.4
    link_threshold: 0.4
    width_ths: 0.5
    height_ths: 0.5

# Dataset Configuration
dataset:
  num_documents: 100
  data_dir: "data/funsd_subset"
  skip_validation: false

# Monitoring Configuration
monitoring:
  enabled: true
  sampling_interval: 2.0  # seconds
  memory_threshold: 0.85
  cpu_threshold: 0.90

# Error Handling
error_handling:
  max_retries: 3
  base_delay: 1.0
  enable_recovery: true
  log_level: "INFO"

# Output Configuration
output:
  generate_reports: true
  save_plots: true
  create_html_report: true
  create_csv_summary: true

# Cost Analysis
cost_analysis:
  electricity_cost_per_kwh: 0.12
  cpu_cost: 500.0
  memory_cost: 200.0
  cpu_lifespan_years: 4.0